/* Unified Admin console for Gia Phả Họ Nguyễn. */
(function(){
'use strict';
const LOG_KEY='giaPhaAdminActivity_v1', REQ_KEY='giaPhaAdminRequests_v1', TREE_KEY='giaPhaNguyenData_v4';
let unlocked=false, activeTab='overview';
const esc=s=>{const d=document.createElement('div');d.textContent=s==null?'':String(s);return d.innerHTML;};
const load=(k,f)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):f;}catch(e){return f;}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function record(action,detail){const rows=load(LOG_KEY,[]);rows.unshift({id:'log_'+Date.now().toString(36),time:new Date().toISOString(),action,detail:detail||'',actor:window.GiaCloud?.state?.profile?.display_name||window.GiaCloud?.state?.user?.email||'Quản trị viên'});save(LOG_KEY,rows.slice(0,300));}
window.GiaAdminLog={record,read:()=>load(LOG_KEY,[])};
function ensureMenu(){
 const more=document.querySelector('#view-more .more-menu'); if(!more)return;
 let btn=document.getElementById('btnAdminMenu');
 if(!btn){btn=document.createElement('button');btn.type='button';btn.id='btnAdminMenu';btn.className='more-item admin-menu-item';btn.dataset.nav='admin';btn.innerHTML='🛡️ <span>Admin</span><small>Quản trị hệ thống</small>';more.insertBefore(btn,more.firstChild);}
 btn.onclick=()=>openGate();
}
function ensureView(){
 let v=document.getElementById('view-admin'); if(v)return v;
 v=document.createElement('section');v.id='view-admin';v.className='view hidden';
 v.innerHTML='<div class="admin-shell">'+
 '<div class="admin-hero"><div class="admin-hero-icon">🛡️</div><div><span>TRUNG TÂM QUẢN TRỊ</span><h2>Admin — Gia Phả Họ Nguyễn</h2><p>Quản lý quyền, thành viên, cây gia phả, dữ liệu và nhật ký trên một màn hình.</p></div><button type="button" id="adminLock" class="admin-lock">🔒 Khóa</button></div>'+
 '<div class="admin-status" id="adminStatus"></div>'+
 '<div class="admin-tabs-main" role="tablist">'+['overview|Tổng quan','roles|Phân quyền','members|Thành viên & Duyệt','tree|Sửa cây gia phả','data|Dữ liệu gia phả','logs|Nhật ký hoạt động'].map(x=>{const [id,label]=x.split('|');return '<button type="button" class="admin-main-tab" data-tab="'+id+'">'+label+'</button>';}).join('')+'</div>'+
 '<div id="adminBody"></div></div>';
 document.getElementById('mainContent')?.appendChild(v);
 v.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;renderTab();});
 document.getElementById('adminLock').onclick=()=>{unlocked=false;window.GiaApp?.lockTreeEditing?.();closeAdmin();};
 return v;
}
async function pinGate(){
 if(unlocked)return true;
 const pin=await window.GiaDialog?.prompt('Nhập mã PIN/Mật khẩu quản trị để mở Trung tâm Admin.','','🔐 Xác thực Admin','Mã PIN / Mật khẩu');
 if(pin==null)return false;
 const ok=window.GiaAdminAuth?.verifyPin?window.GiaAdminAuth.verifyPin(pin):String(pin)==='482916';
 if(!ok){await window.GiaDialog?.alert('Mã PIN không đúng.','Từ chối truy cập');return false;}
 unlocked=true;record('Đăng nhập Admin','Mở Trung tâm quản trị');return true;
}
async function openGate(){if(!(await pinGate()))return;const v=ensureView();document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));v.classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.nav==='more'));renderTab();window.scrollTo(0,0);}
function closeAdmin(){document.getElementById('view-admin')?.classList.add('hidden');window.GiaApp?.showView('home');}
function setStatus(){const p=window.GiaCloud?.state?.profile||{}, role=p.role||p.family_role||p.member_role||'member';const el=document.getElementById('adminStatus');if(el)el.innerHTML='<span>🔐 Đã xác thực Admin</span><b>'+esc(p.display_name||'Quản trị viên')+'</b><em>'+esc(role==='truongho'?'Trưởng họ':role==='admin'?'Admin':'Quyền cục bộ')+'</em>';}
function renderTab(){if(!unlocked)return;setStatus();const v=ensureView();v.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===activeTab));const body=document.getElementById('adminBody');if(!body)return;({overview:renderOverview,roles:renderRoles,members:renderMembers,tree:renderTreeAdmin,data:renderData,logs:renderLogs}[activeTab]||renderOverview)(body);}
function renderOverview(box){const people=load(TREE_KEY,{people:{}}).people||{};const logs=load(LOG_KEY,[]);const req=load(REQ_KEY,[]).filter(x=>x.status==='pending');const cloud=window.GiaCloud;box.innerHTML='<div class="admin-stat-grid"><div><strong>'+Object.keys(people).length+'</strong><span>Thành viên cây</span></div><div><strong>'+logs.length+'</strong><span>Nhật ký</span></div><div><strong>'+req.length+'</strong><span>Yêu cầu chờ xử lý</span></div><div><strong>'+(cloud?.state?.user?'Đã đăng nhập':'Chưa đăng nhập')+'</strong><span>Tài khoản hiện tại</span></div></div><div class="admin-card"><h3>⚡ Thao tác nhanh</h3><div class="admin-quick"><button data-go="members">👥 Quản lý thành viên</button><button data-go="tree">🌳 Mở trình sửa cây</button><button data-go="data">💾 Sao lưu / khôi phục</button><button data-go="logs">📜 Xem nhật ký</button></div></div><div class="admin-note">ℹ️ Màn hình <b>Gia phả → Chỉ xem</b> vẫn là trạng thái an toàn mặc định. Chỉ khi tài khoản có quyền và đã xác thực PIN mới mở được chỉnh sửa.</div>';
 box.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.go;renderTab();});}
async function renderRoles(box){box.innerHTML='<div class="admin-card"><h3>🛡️ Phân quyền tài khoản</h3><p class="muted">Chỉ tài khoản đang có quyền Admin mới được cấp/thu hồi Admin hoặc Trưởng họ. Quyền Trưởng họ cũng được liên kết với chế độ chỉnh sửa cây.</p><div id="roleList">Đang tải…</div></div>';if(!window.GiaCloud?.listMembers){box.querySelector('#roleList').textContent='Tài khoản cloud chưa sẵn sàng.';return;}try{const rows=await window.GiaCloud.listMembers();const me=window.GiaCloud.state.user?.id;box.querySelector('#roleList').innerHTML=(rows||[]).map(m=>{const role=m.role||'member';return '<div class="admin-user-row"><div><strong>'+esc(m.display_name||'Chưa đặt tên')+'</strong><div class="muted">'+esc(m.email||'')+'</div></div><span class="admin-role '+role+'">'+esc(role==='truongho'?'Trưởng họ':role==='admin'?'Admin':'Thành viên')+'</span><div class="admin-user-actions">'+(m.id===me?'<small>Tài khoản hiện tại</small>':role!=='admin'?'<button data-role="admin" data-id="'+esc(m.id)+'">Cấp Admin</button>':'<button class="danger" data-role="member" data-id="'+esc(m.id)+'">Thu hồi Admin</button>')+(m.id!==me&&role!=='admin'?'<button data-role="truongho" data-id="'+esc(m.id)+'">Cấp Trưởng họ</button>':'')+(m.id!==me&&role==='truongho'?'<button class="danger" data-role="member" data-id="'+esc(m.id)+'">Thu hồi Trưởng họ</button>':'')+'</div></div>';}).join('')||'<p class="muted">Chưa có thành viên.</p>';if(!window.GiaCloud.isAdmin?.()){box.querySelector('.admin-card').insertAdjacentHTML('afterbegin','<div class="admin-warning">🔒 Tài khoản hiện tại không phải Admin cloud. Phần cấp quyền sẽ chỉ đọc.</div>');box.querySelectorAll('[data-role]').forEach(b=>b.disabled=true);}box.querySelectorAll('[data-role]').forEach(b=>b.onclick=async()=>{if(!window.GiaCloud.isAdmin?.()){await window.GiaDialog?.alert('Chỉ Admin hiện tại mới được thay đổi quyền.','Phân quyền');return;}const label=b.dataset.role==='admin'?'Admin':b.dataset.role==='truongho'?'Trưởng họ':'Thành viên';if(!(await window.GiaDialog?.confirm('Cấp/đổi quyền thành '+label+' cho thành viên này?','Xác nhận phân quyền')))return;try{await window.GiaCloud.setMemberStatus(b.dataset.id,'approved');await window.GiaCloud.setMemberRole(b.dataset.id,b.dataset.role);record('Thay đổi quyền',label+' · '+b.dataset.id);renderTab();}catch(e){await window.GiaDialog?.alert('Không thể thay đổi quyền: '+(e?.message||e),'Phân quyền');}});}catch(e){box.querySelector('#roleList').innerHTML='<p class="warn-text">'+esc(e?.message||e)+'</p>';}}
async function renderMembers(box){box.innerHTML='<div class="admin-card"><h3>👥 Quản lý thành viên & Phê duyệt</h3><div class="admin-filter-row"><button data-filter="all">Tất cả</button><button data-filter="pending">Chờ duyệt</button><button data-filter="approved">Đã duyệt</button><button data-filter="rejected">Từ chối</button></div><div id="memberList">Đang tải…</div></div>';let rows=[];try{rows=await window.GiaCloud?.listMembers?.()||[];}catch(e){box.querySelector('#memberList').innerHTML='<p class="warn-text">'+esc(e?.message||e)+'</p>';return;}const render=f=>{let r=rows;if(f!=='all')r=r.filter(x=>(x.status||'approved')===f);box.querySelector('#memberList').innerHTML=r.map(m=>'<div class="admin-user-row"><div><strong>'+esc(m.display_name||'Chưa đặt tên')+'</strong><div class="muted">'+esc(m.email||'')+'</div></div><span class="admin-role '+(m.status||'approved')+'">'+esc(m.status==='pending'?'Chờ duyệt':m.status==='rejected'?'Từ chối':'Đã duyệt')+'</span><div class="admin-user-actions">'+(m.status!=='approved'?'<button data-act="approve" data-id="'+esc(m.id)+'">✅ Duyệt</button>':'')+(m.status!=='rejected'?'<button class="danger" data-act="reject" data-id="'+esc(m.id)+'">Từ chối</button>':'')+'</div></div>').join('')||'<p class="muted">Không có thành viên trong nhóm này.</p>';box.querySelectorAll('[data-act]').forEach(b=>b.onclick=async()=>{if(!window.GiaCloud?.isAdmin?.()){await window.GiaDialog?.alert('Chỉ Admin mới được phê duyệt.','Phê duyệt');return;}try{await window.GiaCloud.setMemberStatus(b.dataset.id,b.dataset.act==='approve'?'approved':'rejected');record('Phê duyệt thành viên',(b.dataset.act==='approve'?'Duyệt: ':'Từ chối: ')+b.dataset.id);await renderMembers(box);}catch(e){await window.GiaDialog?.alert('Lỗi: '+(e?.message||e),'Phê duyệt');}});};box.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>render(b.dataset.filter));render('all');}
function renderTreeAdmin(box){box.innerHTML='<div class="admin-card"><h3>🌳 Sửa cây gia phả</h3><p>Admin không sửa dữ liệu bằng một giao diện khác. Nút dưới đây mở đúng màn hình Cây gia phả và liên kết trực tiếp với trạng thái <b>Chỉ xem / Chỉnh sửa</b> hiện có.</p><div class="admin-tree-status">'+(window.GiaApp?.isTreeWriteUnlocked?.()?'🔓 Đang mở chỉnh sửa':'👁️ Đang chỉ xem')+'</div><div class="admin-quick"><button id="adminTreeOpen">🌳 Mở Cây gia phả</button><button id="adminTreeUnlock">🔓 Xác thực để chỉnh sửa</button><button id="adminTreeLock">🔒 Khóa lại</button></div></div><div class="admin-note">Sau khi khóa, các nút thêm/sửa/xóa trên cây bị khóa trở lại. Không tạo một quyền chỉnh sửa thứ hai.</div>';box.querySelector('#adminTreeOpen').onclick=()=>window.GiaApp?.showView('tree');box.querySelector('#adminTreeUnlock').onclick=async()=>{if(await window.GiaApp?.requestTreeWriteAccess?.()){record('Mở quyền sửa cây','Admin mở chế độ chỉnh sửa');renderTab();}};box.querySelector('#adminTreeLock').onclick=()=>{window.GiaApp?.lockTreeEditing?.();record('Khóa quyền sửa cây','Đưa cây về Chỉ xem');renderTab();};}
function renderData(box){box.innerHTML='<div class="admin-card"><h3>💾 Dữ liệu gia phả</h3><p class="muted">Khu vực này đã được đưa vào Admin. Không còn cần một mục “Dữ liệu gia phả” riêng trong menu Thêm.</p><div class="admin-data-actions"><button id="adminExport">⬇️ Xuất JSON</button><button id="adminImport">⬆️ Nhập JSON</button><input id="adminImportFile" type="file" accept=".json" hidden/><button id="adminReset" class="danger">⚠️ Reset dữ liệu mẫu</button></div><div class="admin-warning">Cảnh báo: Nhập/Reset sẽ thay đổi dữ liệu cây đang lưu trên thiết bị. Hãy Xuất JSON trước khi thao tác.</div></div>';box.querySelector('#adminExport').onclick=exportData;box.querySelector('#adminImport').onclick=()=>box.querySelector('#adminImportFile').click();box.querySelector('#adminImportFile').onchange=e=>importData(e.target.files?.[0]);box.querySelector('#adminReset').onclick=resetData;}
function exportData(){const keys=['giaPhaNguyenData_v4','giaPhaEvents_v1','giaPhaPosts_v1','giaPhaChat_v1','giaPhaFamilyFund_v1','giaPhaLiaison_v1'];const payload={version:2,exportedAt:new Date().toISOString(),keys:{}};keys.forEach(k=>{const raw=localStorage.getItem(k);if(raw)try{payload.keys[k]=JSON.parse(raw);}catch(e){payload.keys[k]=raw;}});const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='gia-pha-nguyen-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();record('Xuất dữ liệu','Tạo file sao lưu JSON');}
async function importData(file){if(!file)return;try{const text=await file.text(),p=JSON.parse(text);if(!p?.keys?.giaPhaNguyenData_v4)throw new Error('Thiếu dữ liệu cây gia phả.');if(!(await window.GiaDialog?.confirm('Nhập dữ liệu sẽ ghi đè bản đang lưu trên thiết bị. Anh đã có bản sao lưu chưa?','Xác nhận nhập JSON')))return;Object.entries(p.keys).forEach(([k,v])=>localStorage.setItem(k,JSON.stringify(v)));record('Nhập dữ liệu','Khôi phục từ JSON');await window.GiaDialog?.alert('Đã nhập dữ liệu. Ứng dụng sẽ tải lại để dùng dữ liệu mới.','Dữ liệu gia phả');location.reload();}catch(e){await window.GiaDialog?.alert('Tệp JSON không hợp lệ: '+(e?.message||e),'Nhập dữ liệu');}}
async function resetData(){if(!(await window.GiaDialog?.confirm('Reset sẽ xóa dữ liệu cây hiện tại trên thiết bị và tải lại dữ liệu mẫu. Hãy Xuất JSON trước. Tiếp tục?','⚠️ Cảnh báo an toàn')))return;if((await window.GiaDialog?.prompt('Gõ RESET để xác nhận.','','Xác nhận Reset','RESET'))!=='RESET')return;['giaPhaNguyenData_v4','giaPhaNguyenData_v3','giaPhaNguyenData_v2','giaPhaNguyenData_v1','giaPhaSeedVersion'].forEach(k=>localStorage.removeItem(k));record('Reset dữ liệu','Tải lại dữ liệu mẫu');location.reload();}
function renderLogs(box){const rows=load(LOG_KEY,[]);box.innerHTML='<div class="admin-card"><div class="admin-log-head"><h3>📜 Nhật ký hoạt động</h3><button id="clearLogs" class="danger">Xóa nhật ký</button></div><p class="muted">Nhật ký lưu tối đa 300 hoạt động trên thiết bị này.</p><div class="admin-logs">'+(rows.length?rows.map(x=>'<div class="admin-log"><time>'+esc(new Date(x.time).toLocaleString('vi-VN'))+'</time><strong>'+esc(x.action)+'</strong><span>'+esc(x.detail)+'</span><small>'+esc(x.actor)+'</small></div>').join(''):'<p class="muted">Chưa có hoạt động.</p>')+'</div></div>';box.querySelector('#clearLogs').onclick=async()=>{if(await window.GiaDialog?.confirm('Xóa toàn bộ nhật ký trên thiết bị?','Nhật ký')){save(LOG_KEY,[]);renderTab();}};}
window.addEventListener('gia-auth-changed',()=>{if(unlocked&&activeTab==='roles')renderTab();});window.addEventListener('gia-profile-changed',()=>{if(unlocked)renderTab();});
setTimeout(ensureMenu,300);setTimeout(ensureMenu,1200);
})();